apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: database
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: db
  ports:
    - protocol: TCP
      port: 5432 
      targetPort: 5432

