apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-04-08T17:31:23Z"
    generation: 1
    labels:
      app: buisybox
    name: buisybox
    namespace: default
    resourceVersion: "6001"
    uid: d0fc3440-c82d-47b0-aedf-6b88343f3373
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: buisybox
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: buisybox
      spec:
        containers:
        - image: buisybox
          imagePullPolicy: Always
          name: buisybox
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2024-04-08T17:31:23Z"
      lastUpdateTime: "2024-04-08T17:31:23Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2024-04-08T17:53:21Z"
      lastUpdateTime: "2024-04-08T17:53:21Z"
      message: ReplicaSet "buisybox-cc65557f8" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2024-04-08T17:33:53Z"
    generation: 2
    labels:
      app: busybox
    name: busybox
    namespace: default
    resourceVersion: "17173"
    uid: f6471a1f-589b-414d-bac1-acdb8a333741
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: busybox
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: busybox
      spec:
        containers:
        - args:
          - -c
          - sleep 3600
          command:
          - /bin/sh
          image: busybox
          imagePullPolicy: Always
          name: busybox
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-04-08T17:33:53Z"
      lastUpdateTime: "2024-04-08T17:41:58Z"
      message: ReplicaSet "busybox-58b89fd447" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-04-10T15:42:17Z"
      lastUpdateTime: "2024-04-10T15:42:17Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
    creationTimestamp: "2024-04-08T17:47:51Z"
    generation: 3
    labels:
      app: busybox2
    name: busybox2
    namespace: default
    resourceVersion: "17542"
    uid: a6235a76-b930-4566-b266-f4fedffe496d
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: busybox2
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: busybox2
      spec:
        containers:
        - args:
          - -c
          - sleep 3600
          command:
          - /bin/sh
          image: busybox
          imagePullPolicy: Always
          name: busybox
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-04-08T17:47:51Z"
      lastUpdateTime: "2024-04-08T17:49:20Z"
      message: ReplicaSet "busybox2-9c5f84dbf" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-04-10T15:49:38Z"
      lastUpdateTime: "2024-04-10T15:49:38Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"proxy"},"name":"proxy","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"proxy"}},"template":{"metadata":{"labels":{"app":"proxy"}},"spec":{"containers":[{"image":"nginx:latest","name":"proxy","ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2024-04-10T15:57:36Z"
    generation: 1
    labels:
      app: proxy
    name: proxy
    namespace: default
    resourceVersion: "18041"
    uid: edbdf296-d848-43a5-8a03-38254527eb15
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: proxy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: proxy
      spec:
        containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: proxy
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2024-04-10T15:57:42Z"
      lastUpdateTime: "2024-04-10T15:57:42Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-04-10T15:57:36Z"
      lastUpdateTime: "2024-04-10T15:57:42Z"
      message: ReplicaSet "proxy-d86559567" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
