apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
