apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
  namespace: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: pandaacademy/result:1.0
        env:
        - name: DB_HOST
          value: "db-svc.database"
        - name: POSTGRES_USER
          value: "ssk"
        - name: POSTGRES_PASSWORD
          value: "ssk"
