apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote 
        image: pandaacademy/vote:1.0
        env:
        - name: REDIS_HOST
          value: "redis-svc.database"
