apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: pandaacademy/worker:1.0
        env:
        - name: POSTGRES_USER
          value: "ssk"
        - name: POSTGRES_PASSWORD
          value: "ssk"
        - name: DB_HOST
          value: "db-svc.database"
        - name: REDIS_HOST
          value: "redis-svc.database"
